apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostPath
metadata:
  name: psp-no-hostpath-volumes
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - audit-zone
      - gatekeeper-test
